require "rails_helper"
RSpec.feature "Create new role" do

  before do
    visit "/roles"
    click_link "New Role"
  end

  scenario "with valid attributes" do
    fill_in "Name", with: "Standard"
    fill_in "Description", with: "Free. Can only view/update public posts"
    click_button "Create Role"  # "Create Role" was generated by form. Have to run form first to see what it generated
    expect(page).to have_content "Role has been created"

    role = Role.find_by(Name: "Standard")
    expect(page.current_url).to eq role_url(role) # make sure this is Show action in role controller
    title = "Wikiiki - Standard - Role" # Show.htmp.erb->application_helper.rb->application.html.erb
    expect(page).to have_title title
  end

  scenario "when providing invalid attributes" do
    click_button "Create Role"
    expect(page).to have_content "Role has not been created."
    expect(page).to have_content "Name can't be blank"
  end

end
