require "rails_helper"
RSpec.feature "Users can create new posts with valid attributes" do
  scenario "with valid attributes" do
    visit "/"
    click_link "New Post"
    fill_in "Title", with: "Sublime Text 3"
    fill_in "Body", with: "A text editor for everyone"
    click_button "Create Post"  # "Create Post" was generated by form. Have to run form first to see what it generated
    expect(page).to have_content "Post has been created"

    post = Post.find_by(title: "Sublime Text 3")
    expect(page.current_url).to eq post_url(post) # make sure this is Show action in post controller
    title = "Wikiiki - Sublime Text 3 - Post" # Show.htmp.erb->application_helper.rb->application.html.erb
    expect(page).to have_title title
  end
end
