require "rails_helper"
RSpec.feature "Create new post" do
  #let(:user) { FactoryGirl.create(:user) }
  before do
    @user = FactoryGirl.create(:user)
    login_as(@user)
    @premium=Role.create!(name:"premium", description: "Paid. Create & Update public and private posts. Ability to collaborate.")
    @admin=Role.create!(name:"admin", description: "Administrator. Do almost everything.")
  end

  scenario "Premium user with valid attributes" do
    Assignment.create!( user: @user, role: @premium)
    visit "/"
    click_link "New Post"
    fill_in "Title", with: "Sublime Text 3"
    fill_in "Body", with: "A text editor for everyone"
    click_button "Create Post"  # "Create Post" was generated by form. Have to run form first to see what it generated
    expect(page).to have_content "Post has been created"

    post = Post.find_by(title: "Sublime Text 3")
    expect(page.current_url).to eq post_url(post) # make sure this is Show action in post controller
    title = "Wikiiki - Sublime Text 3 - Post" # Show.htmp.erb->application_helper.rb->application.html.erb
    expect(page).to have_title title
  end

  scenario "Premium user with invalid attributes" do
    Assignment.create!( user: @user, role: @premium)
    visit "/"
    click_link "New Post"
    click_button "Create Post"
    expect(page).to have_content "Post has not been created."
    expect(page).to have_content "Title can't be blank"
  end

  scenario "Admin user with valid attributes" do
    Assignment.create!( user: @user, role: @admin)
    visit "/"
    click_link "New Post"
    fill_in "Title", with: "Sublime Text 3"
    fill_in "Body", with: "A text editor for everyone"
    click_button "Create Post"  # "Create Post" was generated by form. Have to run form first to see what it generated
    expect(page).to have_content "Post has been created"

    post = Post.find_by(title: "Sublime Text 3")
    expect(page.current_url).to eq post_url(post) # make sure this is Show action in post controller
    title = "Wikiiki - Sublime Text 3 - Post" # Show.htmp.erb->application_helper.rb->application.html.erb
    expect(page).to have_title title
  end

  scenario "Admin user with invalid attributes" do
    Assignment.create!( user: @user, role: @admin)
    visit "/"
    click_link "New Post"
    click_button "Create Post"
    expect(page).to have_content "Post has not been created."
    expect(page).to have_content "Title can't be blank"
  end

end
