require "rails_helper"
RSpec.feature "Deleting posts" do
  before do
    @user = FactoryGirl.create(:user)
    login_as(@user)
    @premium=Role.create!(name:"premium", description: "Paid. Create & Update public and private posts. Ability to collaborate.")
    @admin=Role.create!(name:"admin", description: "Administrator. Do almost everything.")
  end

  scenario "As Premium user deleting own post" do
    Assignment.create!( user: @user, role: @premium)
    visit "/"
    click_link "New Post"
    fill_in "Title", with: "Sublime Text 3"
    fill_in "Body", with: "A text editor for everyone"
    click_button "Create Post"  # "Create Post" was generated by form. Have to run form first to see what it generated
    expect(page).to have_content "Post has been created"

    visit "/"
    click_link "Sublime Text 3"
    click_link "Delete Post"
    expect(page).to have_content "Post has been deleted."
    expect(page).to have_no_link "Sublime Text 3"
  end

end
